version: "3"
services:
  php:
    image: php:latest
    volumes:
      - ./data/php:/var/www/myapp
      - ./data/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: rootroot

    volumes:
      - mariadb-data:/var/lib/mysql
      - "./data/db:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 3000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
volumes:
  mariadb-data:
