version: "3.8"
services:
  web:
    build: ./front-end
    ports:
      - 3000:3000
  api:
    build: ./back-end
    ports:
      - 3001:3001
    environment:
      - DB_URL=
  db:
    image: mariadb:10.4 
    ports:
      - 3306:3306
    volumes:
      - LCS-Development/data/db
volumes:
  LCS-Development:
